[package]
name = "rrbe-address-port"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.21.4"
clap-v3 = "3.0.0-beta.1"