[package]
name = "consumer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap-v3 = "3.0.0-beta.1"
redis = "0.21.4"
hostname = "0.3.0"
rs_util = { path = "../../../rs_util" }
